# Generated by Django 5.0.14 on 2026-07-30 17:54

import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantUser",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(default=True)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="tenants.application",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_tenant_user",
            },
        ),
        migrations.CreateModel(
            name="BiometricProfile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("embedding", pgvector.django.vector.VectorField(dimensions=512)),
                (
                    "model_version",
                    models.CharField(
                        choices=[
                            ("buffalo_s", "InsightFace buffalo_s"),
                            ("mobilefacenet", "MobileFaceNet"),
                        ],
                        default="buffalo_s",
                        max_length=30,
                    ),
                ),
                (
                    "liveness_score",
                    models.FloatField(
                        help_text="Score de anti-spoofing pasivo al momento del enrolamiento."
                    ),
                ),
                ("quality_score", models.FloatField(blank=True, null=True)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Desactiva un embedding antiguo al re-enrolar sin perder histórico.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_profiles",
                        to="tenants.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="biometric_profiles",
                        to="accounts.tenantuser",
                    ),
                ),
            ],
            options={
                "db_table": "accounts_biometric_profile",
            },
        ),
        migrations.AddIndex(
            model_name="tenantuser",
            index=models.Index(
                fields=["application", "email"], name="accounts_te_applica_d40f33_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="tenantuser",
            constraint=models.UniqueConstraint(
                fields=("application", "email"), name="uniq_email_per_app"
            ),
        ),
        migrations.AddIndex(
            model_name="biometricprofile",
            index=pgvector.django.indexes.HnswIndex(
                ef_construction=64,
                fields=["embedding"],
                m=16,
                name="biometric_embedding_hnsw_idx",
                opclasses=["vector_cosine_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="biometricprofile",
            index=models.Index(
                fields=["application", "is_active"],
                name="accounts_bi_applica_652063_idx",
            ),
        ),
    ]
