# Generated by Django 5.0.14 on 2026-07-30 17:54

import apps.tenants.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_enable_pgvector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app_id",
                    models.CharField(
                        db_index=True,
                        default=apps.tenants.models.generate_app_id,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "api_key",
                    models.CharField(
                        default=apps.tenants.models.generate_api_key,
                        editable=False,
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "redirect_uris",
                    models.JSONField(
                        default=list,
                        help_text="Whitelist de URLs a las que se permite redirigir tras un login exitoso.",
                    ),
                ),
                (
                    "liveness_threshold",
                    models.FloatField(
                        default=0.85,
                        help_text="Score mínimo (0-1) del modelo de liveness pasivo para aceptar el intento.",
                    ),
                ),
                (
                    "match_threshold",
                    models.FloatField(
                        default=0.42,
                        help_text="Distancia coseno máxima aceptada entre embedding capturado y almacenado.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "tenants_application",
                "ordering": ["-created_at"],
            },
        ),
    ]
