# Generated by Django 5.0.14 on 2026-07-30 20:59

import apps.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="api_key_rotated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Última rotación de api_key (None = clave original de creación).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="api_key",
            field=models.CharField(
                default=apps.tenants.models.generate_api_key,
                editable=False,
                help_text="Secreto de integración del tenant. Rotar con `rotate_api_key`.",
                max_length=64,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="redirect_uris",
            field=models.JSONField(
                default=list,
                help_text="Whitelist exacta de URLs a las que se permite redirigir tras login.",
            ),
        ),
    ]
