# Generated by Django 5.0.14 on 2026-08-22 01:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("tenants", "0003_add_api_key_rotated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpChallenge",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("email_verify", "Verificación de email"),
                            ("step_up", "Step-up de acción sensible"),
                            ("account_unlock", "Desbloqueo de cuenta"),
                            ("email_change", "Cambio de email"),
                            ("reenrollment", "Re-enrolamiento biométrico"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("sms", "SMS"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        default="email",
                        max_length=16,
                    ),
                ),
                ("destination_hash", models.CharField(max_length=64)),
                ("code_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(blank=True, null=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("attempt_count", models.PositiveSmallIntegerField(default=0)),
                ("invalidated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "application",
                    models.ForeignKey(
                        editable=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_challenges",
                        to="tenants.application",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="otp_challenges",
                        to="accounts.tenantuser",
                    ),
                ),
            ],
            options={
                "db_table": "otp_challenge",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "-created_at"],
                        name="otp_challen_user_id_6162d3_idx",
                    ),
                    models.Index(
                        fields=["user", "purpose", "consumed_at", "invalidated_at"],
                        name="otp_challen_user_id_290788_idx",
                    ),
                ],
            },
        ),
    ]
